name: Hello World Workflow

on: 
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello World
      run: echo "Hello World!"

    - name: Print date
      run: date

    - name: Print directory Contents
      run: ls -l
    
